version: 2
jobs:
  system:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Continuous Integration checks
          command: |
            npm run lint && npm test
            
workflows:
  version: 2
  main:
    jobs:
      - system            
